// <auto-generated />
using System;
using CinemaManagement.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CinemaManagement.DAL.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20260923142804_UpdateDbFromGitHub")]
    partial class UpdateDbFromGitHub
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CinemaApp.Common.Entities.SeatTypeSurcharge", b =>
                {
                    b.Property<int>("LoaiGhe")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTienPhuThu")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("LoaiGhe");

                    b.ToTable("LoaiGhePhuThu", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("text");

                    b.Property<int>("HanhDong")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.CinemaRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SoCot")
                        .HasColumnType("integer");

                    b.Property<int>("SoHang")
                        .HasColumnType("integer");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenPhong")
                        .IsUnique();

                    b.ToTable("PhongChieu", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Combo", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("SDT")
                        .IsUnique();

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiNhan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("LoiNeuCo")
                        .HasColumnType("text");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("LichSuGuiEmail", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("TrangThaiLamViec")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenTheLoai")
                        .IsUnique();

                    b.ToTable("TheLoai", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PhuongThuc")
                        .HasColumnType("integer");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TrangThaiThanhToan")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.InvoiceCombo", b =>
                {
                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("ComboId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DonGiaLucMua")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("InvoiceId", "ComboId");

                    b.HasIndex("ComboId");

                    b.ToTable("HoaDonCombo", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DaoDien")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DienVien")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DoTuoi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayKhoiChieu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Poster")
                        .HasColumnType("text");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Phim", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("Phim_TheLoai", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("MaGiaoDichVNPay")
                        .HasColumnType("text");

                    b.Property<string>("MaPhanHoi")
                        .HasColumnType("text");

                    b.Property<string>("NoiDungIPN")
                        .HasColumnType("text");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("GiaoDichThanhToan", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyen")
                        .IsUnique();

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("VaiTro_Quyen", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaRoomId")
                        .HasColumnType("integer");

                    b.Property<int>("Cot")
                        .HasColumnType("integer");

                    b.Property<int>("Hang")
                        .HasColumnType("integer");

                    b.Property<int>("LoaiGhe")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CinemaRoomId", "Hang", "Cot")
                        .IsUnique();

                    b.ToTable("Ghe", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.SeatShowtimeStatus", b =>
                {
                    b.Property<int>("ShowtimeId")
                        .HasColumnType("integer");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ThoiGianGiu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("ShowtimeId", "SeatId");

                    b.HasIndex("SeatId");

                    b.ToTable("TrangThaiGheTheoSuat", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Showtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaRoomId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GiaVeCoSo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("interval");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayChieu")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CinemaRoomId");

                    b.HasIndex("MovieId");

                    b.ToTable("SuatChieu", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("MaQR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ThoiGianCheckIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TrangThaiCheckIn")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("MaQR")
                        .IsUnique();

                    b.HasIndex("SeatId");

                    b.HasIndex("ShowtimeId", "SeatId")
                        .IsUnique();

                    b.ToTable("Ve", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LanSaiCuoiCung")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("SoLanBiKhoa")
                        .HasColumnType("integer");

                    b.Property<int>("SoLanSaiMatKhau")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ThoiGianKhoaDenLuc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TrangThaiTaiKhoan")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.AuditLog", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.EmailLog", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Employee", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("CinemaManagement.Common.Entities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Invoice", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CinemaManagement.Common.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.InvoiceCombo", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaManagement.Common.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceCombos")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.MovieGenre", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaManagement.Common.Entities.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Payment", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.RolePermission", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaManagement.Common.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Seat", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.CinemaRoom", "CinemaRoom")
                        .WithMany("Seats")
                        .HasForeignKey("CinemaRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaRoom");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.SeatShowtimeStatus", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaManagement.Common.Entities.Showtime", "Showtime")
                        .WithMany("SeatStatuses")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Showtime", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.CinemaRoom", "CinemaRoom")
                        .WithMany("Showtimes")
                        .HasForeignKey("CinemaRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaManagement.Common.Entities.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CinemaRoom");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Ticket", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.Invoice", "Invoice")
                        .WithMany("Tickets")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaManagement.Common.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaManagement.Common.Entities.Showtime", "Showtime")
                        .WithMany()
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Seat");

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.User", b =>
                {
                    b.HasOne("CinemaManagement.Common.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.CinemaRoom", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceCombos");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Movie", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CinemaManagement.Common.Entities.Showtime", b =>
                {
                    b.Navigation("SeatStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
